version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--zookeeper", "zookeeper:2181", "--list"]
      interval: 10s
      timeout: 10s
      retries: 6

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  inbound-telemetry-service:
    build: ./InboundTelemetryService
    ports:
      - "80:80"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BROKER: kafka:9092
      OUTPUT_KAFKA_TOPIC: inbound-telemetry

  telemetry-writing-service:
    build: ./DataWritingService
    depends_on:
      - kafka
      - mongo
    environment:
      SERVICE_IDENTIFIER: telemetry-writing-service
      KAFKA_BROKER: kafka:9092
      INPUT_KAFKA_TOPIC: inbound-telemetry
      OUTPUT_MONGO_URI: mongodb://mongo:27017
      OUTPUT_MONGO_DB: gos_mongo
      OUTPUT_MONGO_COLLECTION: inbound_telemetry
    restart: always

  telemetry-ingest-service:
    build: ./TelemetryIngestService
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BROKER: kafka:9092
      INPUT_KAFKA_TOPIC: inbound-telemetry
      OUTPUT_KAFKA_TOPIC: branch-energy

  branch-energy-writing-service:
    build: ./DataWritingService
    depends_on:
      - kafka
      - mongo
    environment:
      SERVICE_IDENTIFIER: branch-energy-writing-service
      KAFKA_BROKER: kafka:9092
      INPUT_KAFKA_TOPIC: branch-energy
      OUTPUT_MONGO_URI: mongodb://mongo:27017
      OUTPUT_MONGO_DB: gos_mongo
      OUTPUT_MONGO_COLLECTION: branch_energy
    restart: always

volumes:
  mongo-data:
